### ISSUE TITLE
LIST 文件报错

### ISSUE THREAD

**Issue by amplatzer** [aliyun/oss-ftp#29]
任意目录  ls  文件名， 返回426 内部错误 。看了下代码 ， modify  值为0。 

2022-11-08 14:52:12,098 DEBUG   [handlers.py:1775(logline)] IPIPIP:52632-[ftp8] <- LIST /a/b/c/d/e/f.pdf
2022-11-08 14:52:12,100 DEBUG   [auth.py:49(__make_signature)] string_to_sign=GET

Tue, 08 Nov 2022 06:52:12 GMT
/tmpftp/
2022-11-08 14:52:12,101 DEBUG   [connectionpool.py:208(_new_conn)] Starting new HTTP connection (1):  xxx
2022-11-08 14:52:12,103 DEBUG   [connectionpool.py:396(_make_request)] http://xxx:80 "GET /?marker=&prefix=f.pdf%2F&max-keys=100&delimiter=%2F&encoding-type=url HTTP/1.1" 200 356
2022-11-08 14:52:12,104 DEBUG   [handlers.py:1775(logline)] IPIPIP:52632-[ftp8] -> 125 Data connection already open. Transfer starting.
2022-11-08 14:52:12,104 DEBUG   [log.py:130(debug)] [debug] starting transfer not using sendfile(2) as per server config (<pyftpdlib.handlers.DTPHandler (addr=IPIPIP:51311, user=u'ftp8', receive=False, file='')>)
2022-11-08 14:52:12,104 DEBUG   [log.py:130(debug)] [debug] starting transfer using send() (<pyftpdlib.handlers.DTPHandler (addr=IPIPIP:51311, user=u'ftp8', receive=False, file='')>)
2022-11-08 14:52:12,104 ERROR   [handlers.py:1786(log_exception)] unhandled exception in instance <pyftpdlib.handlers.DTPHandler (addr=IPIPIP:51311, user=u'ftp8', receive=False, file='')>
Traceback (most recent call last):
  File "/root/ossftp-1.2.0-linux-mac/python27/unix/lib/pyftpdlib/handlers.py", line 1713, in push_dtp_data
    self.data_channel.push_with_producer(data)
  File "/root/ossftp-1.2.0-linux-mac/python27/unix/lib/pyftpdlib/handlers.py", line 653, in push_with_producer
    AsyncChat.push_with_producer(self, producer)
  File "/usr/lib64/python2.7/asynchat.py", line 190, in push_with_producer
    self.initiate_send()
  File "/root/ossftp-1.2.0-linux-mac/python27/unix/lib/pyftpdlib/handlers.py", line 659, in initiate_send
    asynchat.async_chat.initiate_send(self)
  File "/usr/lib64/python2.7/asynchat.py", line 226, in initiate_send
    data = first.more()
  File "/root/ossftp-1.2.0-linux-mac/python27/unix/lib/pyftpdlib/handlers.py", line 1052, in more
    buffer.append(next(self.iterator))
  File "/root/ossftp-1.2.0-linux-mac/ossftp/oss_fs.py", line 144, in format_list
    mtimestr = "%s %s" % (_months_map[int(modify[5:7])],
TypeError: 'int' object has no attribute '__getitem__'
2022-11-08 14:52:12,106 DEBUG   [log.py:130(debug)] [debug] call: close() (<pyftpdlib.handlers.DTPHandler (addr=IPIPIP:51311, user=u'ftp8', receive=False, file='')>)

**Comment by amplatzer** [comment]
而且list  出来的文件的 size 为什么显示为0

**Comment by amplatzer** [comment]
def get_list_dir(self, path):
        assert isinstance(path, unicode), path
        if self.isdir(path):
            listing = self.listdir(path)
            try:
                listing.sort()
            except UnicodeDecodeError:
                pass
            return self.format_list(path, listing)
        else:
            basedir, filename = os.path.split(path)
            return self.format_list(basedir, [(filename, 0, 0)])
           

这里是偷懒了吗， 有getsize  和 getmtime 为什么直接传0 啊。。
