### ISSUE TITLE
Centos运行oss-ftp报错

### ISSUE THREAD

**Issue by xiaoyuxiaoyu** [aliyun/oss-ftp#7]
报错信息:
[root@localhost ossftp-1.0.2-win]# bash start.sh 
Traceback (most recent call last):
  File "launcher/start.py", line 19, in <module>
    from ossftp.ftpd import FTPd
  File "/home/ossftp/ossftp-1.0.2-win/ossftp/__init__.py", line 3, in <module>
    from .oss_authorizers import OssAuthorizer
  File "/home/ossftp/ossftp-1.0.2-win/ossftp/oss_authorizers.py", line 22, in <module>
    from pyftpdlib.authorizers import DummyAuthorizer
ImportError: No module named pyftpdlib.authorizers
我python使用默认版本2.6.6报错，最后我升级到2.7仍然报同样的错误.

**Comment by johnkeepmoving** [comment]
请参考https://help.aliyun.com/document_detail/32190.html
centos请用 ossftp-1.0.2-linux-mac.zip

**Comment by xiaoyuxiaoyu** [comment]
我就是参考这个啊，启动脚本的时候报错了。另外ossftp是不是使用了一些被动端口，我把防火墙关掉登录子账户后就会列出oss的目录，如果不关掉就不会列出这些目录

**Comment by xiaoyuxiaoyu** [comment]
报错好了，我给下错了。ossftp是不是使用了一些被动端口，我把防火墙关掉登录子账户后就会列出oss的目录，如果不关掉就不会列出这些目录。2048端口已加入防火墙，并在ftp工具中看到已登录成功，但是开着防火墙就无法列出oss目录
